### ISSUE TITLE
Feature Request: please add falcon 7b mamba support

### ISSUE THREAD

**Issue by MobinX** [ggerganov/llama.cpp#9048] opened 2024-08-15 19:16 UTC
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

please add falcon 7b mamba support ,

https://huggingface.co/tiiuae/falcon-mamba-7b-instruct
### Motivation

please add falcon 7b mamba support ,

https://huggingface.co/tiiuae/falcon-mamba-7b-instruct
### Possible Implementation

please add falcon 7b mamba support ,

https://huggingface.co/tiiuae/falcon-mamba-7b-instruct

**Comment by jeroen-mostert** [comment] 2024-08-15 23:49
Charming duplicate of #9009.

**Closed** 2024-08-21 08:06 UTC
Labels: enhancement
