### ISSUE TITLE
Chinese character decoding error when intract way

### ISSUE THREAD

**Issue by jinfagang** [ggerganov/llama.cpp#86] opened 2023-03-13 08:21 UTC
<img width="463" alt="image" src="https://user-images.githubusercontent.com/21303438/224645334-fed2e1d7-c858-49c7-b8bc-341fbb01ead3.png">

can not handle Chinese.

**Comment by wizd** [comment] 2023-03-13 09:29
you can try PR https://github.com/ggerganov/llama.cpp/pull/87

**Comment by prusnak** [comment] 2023-03-13 09:52
Duplicate of https://github.com/ggerganov/llama.cpp/issues/11

**Closed by prusnak** 2023-03-13 09:52 UTC
