### ISSUE TITLE
Using the latest llama-cli will result in an output that keeps blanking

### ISSUE THREAD

**Issue by QIANXUNZDL123** [ggerganov/llama.cpp#8253] opened 2024-07-02 09:21 UTC
### What happened?

I enter： who is Elon Mask?  and after replying to a paragraph, the cursor starts to move all the way down. If you don't stop him, he'll keep going down
![image](https://github.com/ggerganov/llama.cpp/assets/46549527/29c5697e-0cdc-4383-a38f-1dcff66f68c0)

### Name and Version

./bin/llama-cli -m ../modelGGUF/llama-2-7b-chat.Q4_0.gguf  -cnv -t 6 --ctx_size 2048 -n -1 -b 256 --top_k 1000 --temp 0.2 --repeat_penalty 1.1

**Comment by ngxson** [comment] 2024-07-02 11:21
You're using an old model that does not have chat template support. Add `--chat-template llama2` to your command

**Comment by dspasyuk** [comment] 2024-07-02 19:54
@QIANXUNZDL123 Switch to llama3-instruct QuantFactory/Meta-Llama-3-8B-Instruct-GGUF, llama2 is ancient, and use template like @ngxson has suggested also for prompt you will need to use: <|start_header_id|>user  check out llama.cui for more details https://github.com/dspasyuk/llama.cui

**Comment by ngxson** [comment] 2024-07-02 20:27
@dspasyuk llama 3 is new model, so llama.cpp has auto chat template support for it.

Simple sun llama 3 with `./llama-cli -m ... -cnv`, no need to worry about special tokens

**Comment by dspasyuk** [comment] 2024-07-02 20:43
@ngxson Yes, I know this is how it was intended to work but if you do stress test it with this setting model starts to goof out after about 3000 tokens, at least in my hands:

../llama.cpp/llama-cli --model ../../models/Meta-Llama-3-8B-Instruct_Q5_K_S.gguf --n-gpu-layers 30 -cnv  --interactive  --interactive-first  --simple-io  -b 2048 -n -1 -e  --ctx_size 0 --temp 0.5 --top_k 10 --multiline-input  --repeat_penalty 1.12 --chat-template llama3 -t 8 -ptc 10 -r "user:"  

Using llama3 template manually work without issues for infinity. I am not sure why there is a difference perhaps the issue is with missing BOS token in the template because llama-cli prints this as a template, which does not have BOS token: 

main: chat template example: <|start_header_id|>system<|end_header_id|>

You are a helpful assistant<|eot_id|><|start_header_id|>user<|end_header_id|>

Hello<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Hi there<|eot_id|><|start_header_id|>user<|end_header_id|>

How are you?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

https://llama.meta.com/docs/model-cards-and-prompt-formats/meta-llama-3/

**Comment by ngxson** [comment] 2024-07-02 20:56
As far as I can tell, BOS is added in conversation mode. main.log says:

```
[1719953638] add_bos: 1
[1719953638] tokenize the prompt
[1719953638] prompt: "<|start_header_id|>system<|end_header_id|>

You are AI<|eot_id|>"
[1719953638] tokens: [ '<|begin_of_text|>':128000, '<|start_header_id|>':128006, 'system':9125, '<|end_header_id|>':128007, '':271, 'You':2675, ' are':527, ' AI':15592, '<|eot_id|>':128009 ]
```

Probably there is something to do with your sampling settings.

**Comment by dspasyuk** [comment] 2024-07-02 21:39
Yes, anything is possible, could not figure it out, so switched to do it manually instead.

**Comment by dspasyuk** [comment] 2024-07-03 02:22
@ngxson I do not think the reverse prompt is modified when --chat-template llama3 is used so using something like this User: is no good.

**Comment by dspasyuk** [comment] 2024-07-03 11:44
Llama-cli sets the reverse prompt in conversation mode in my logs, as for the manuals it says here.... see below, or do I missunderstand that?

Reverse Prompts
Reverse prompts are a powerful way to create a chat-like experience with a LLaMA model by pausing the text generation when specific text strings are encountered:

-r PROMPT, --reverse-prompt PROMPT: Specify one or multiple reverse prompts to pause text generation and switch to interactive mode. For example, -r "User:" can be used to jump back into the conversation whenever it's the user's turn to speak. This helps create a more interactive and conversational experience. However, the reverse prompt doesn't work when it ends with a space.

**Comment by ngxson** [comment] 2024-07-03 11:56
Reverse prompts / insuffix / inprefix are used before there is chat template support. They are a different system.

Can you just post your main.log here? Without log data I can't see the bug.

**Comment by ngxson** [comment] 2024-07-03 12:36
The reason why you got this result is because only chat template OR inprefix/suffix system can exist at the same time.

Instead of adding a lot of options, you should try with simple command at once (instead of the how big command) to isolate the problem:

```
../llama.cpp/llama-cli --model ../../models/Meta-Llama-3-8B-Instruct_Q5_K_S.gguf -cnv
../llama.cpp/llama-cli --model ../../models/Meta-Llama-3-8B-Instruct_Q5_K_S.gguf -cnv --chat-template llama3
../llama.cpp/llama-cli --model ../../models/Meta-Llama-3-8B-Instruct_Q5_K_S.gguf -cnv --chat-template llama3 --no-display-prompt

...
```

**Comment by dspasyuk** [comment] 2024-07-03 13:01
@ngxson  Than kyou for your help. Running just this  ../llama.cpp/llama-cli --model ../../models/Meta-Llama-3-8B-Instruct_Q5_K_S.gguf --n-gpu-layers 25 -cnv --multiline-input --chat-template llama3 

Producing about the same result as this: ../llama.cpp/llama-cli --model ../../models/Meta-Llama-3-8B-Instruct_Q5_K_S.gguf --n-gpu-layers 25 -cnv --interactive --interactive-first --simple-io -b 2048 -n -1 -e --ctx_size 0 --temp 0.5 --top_k 10 --multiline-input --repeat_penalty 1.12 -t 8 -ptc 10 --chat-template llama3 -r "<|start_header_id|>user" --logdir ./ --log-append --no-display-prompt

Generation eventually just stops after about 5000 tokens but resumes no issue and does not hallucinate.  The difference I see between manual prompting and llama3 template is that in the template version, it uses bos token only at the beginning and in the manual prompting it looks something like this: input tokens: [ '<|start_header_id|>':128006, 'user':882, '<|end_header_id|>':128007, '':271, '<|begin_of_text|>':128000, '<|start_header_id|>':128006, 'system':9125, '<|end_header_id|>':128007, '':271, 'Role':9207, ' and':323, ' Purpose':30145, ':':25, ' You':1472, ' are':527, ' Alice':30505, ',':11, ' a':264, ' large':3544, ' language':4221, ' model':1646, 

And I do not instert these: [ '<|start_header_id|>':128006, 'user':882, '<|end_header_id|>':128007, '':271, 

I starts the message here: '<|begin_of_text|>':128000, '<|start_header_id|>':128006, 'system':9125, '<|end_header_id|>':128007, '':271, 'Role':9207, ' and':323, ' Purpose':30145, ':':25, ' You':1472, ' are':527, ' Alice':30505, ',':11, ' a':264, ' large':3544, ' language':4221, ' model':1646,

**Comment by dspasyuk** [comment] 2024-07-03 13:06
Actually, there is no need to set  --chat-template option at all if it is present in the model metadata. Llama-cli sets by itself.

**Comment by ngxson** [comment] 2024-07-03 13:06
The correct template of llama3 is to have bos at the beginning, not at the start of every message.

Read the original jinja template (don't read the docs) and you will see: https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/blob/main/tokenizer_config.json

Again, don't assume how things work if you haven't read the code.

**Comment by dspasyuk** [comment] 2024-07-03 13:09
@ngxson  I know, but like I said, this is what works without any issue.

**Comment by ngxson** [comment] 2024-07-03 13:12
Here we're follow the "standard" provided by the original model (i.e. the one uploaded by meta on huggingface). If there are problems with it, then it's a bug with the original model, not inside llama.cpp

> Actually, there is no need to set --chat-template option at all if it is present in the model metadata. Llama-cli sets by itself.

Chat template is auto detected if the model has built-in template. Again, this template is decided by the original model on huggingface. Llama 3 has that, but not for llama 2 since meta doesn't update it.

**Comment by dspasyuk** [comment] 2024-07-03 13:26
@ngxson I agree it could well be an issue with the model itself. It's just hard to know what causes it with all the changes to the llama-cpp. This issue was not there in version 3077. And llama3-instruct 8B is kind of the best model right now.

**Comment by dspasyuk** [comment] 2024-07-03 13:48
@ngxson I am not sure why <|eot_id|> gets inserted sometime in the meedle of answering the questions with the default template and not with the manual prompt formating it happens also kind of random:  [1720014136] last: [ ' To':2057, ' find':1505, ' the':279, ' flight':11213, ' time':892, ':':1473, 'Flight':46405, ' Time':4212, ' =':284, ' Distance':32235, ' /':611, ' Speed':15535, '':198, '=':28, ' ':220, '345':12901, '9':24, ' miles':8931, ' /':611, ' ':220, '550':13506, ' mph':35061, '':198, '':60094, '':230, ' ':220, '6':21, '.':13, '3':18, ' hours':4207, '':271, 'Since':12834, ' you':499, ' want':1390, ' to':311, ' know':1440, ' the':279, ' number':1396, ' of':315, ' days':2919, ',':11, ' we':584, ' need':1205, ' to':311, ' convert':5625, ' this':420, ' to':311, ' hours':4207, ':':1473, '1':16, ' day':1938, ' =':284, ' ':220, '24':1187, ' hours':4207, '':271, 'So':4516, ',':11, ' the':279, ' travel':5944, ' time':892, ' is':374, ' approximately':13489, '<|eot_id|>':128009 ]
[1720014136] n_remain: -4933
[1720014136] found an EOG token
[1720014136] waiting for user input

**Comment by dspasyuk** [comment] 2024-07-03 15:26
@ngxson do you if there is a way to force no template like  --chat-template "none"?

**Comment by ngxson** [comment] 2024-07-03 15:30
Chat template is deactivated if one of in-suffix/prefix is set. Again, if you want to play around, take time to read the code:

https://github.com/ggerganov/llama.cpp/blob/916248af1f3c16abd7408de848e025da095c621c/common/common.cpp#L1015-L1030

**Comment by dspasyuk** [comment] 2024-07-03 15:51
@ngxson thank you for reply, I have seen that in the code but when I set prefix and suffix to some string I still get the default template keywords " input tokens: [ '<|start_header_id|> etc ..... : LOG here:

[1720021639] adding input prefix BOS token
[1720021651] buffer: '<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Role and Purpose: You are Alice, a large language model. Your purpose is to assist users by providing information, answering questions, and engaging in meaningful conversations based on the data you were trained on. Behavior and Tone:  Be informative, engaging, and respectful. Maintain a neutral and unbiased tone. Ensure that responses are clear and concise. Capabilities: Use your training data to provide accurate and relevant information. Explain complex concepts in an easy-to-understand manner.Provide sources when referencing specific information or data. Output Formatting: Use this formatting for code: ```language /n```<|eot_id|><|start_header_id|>user<|end_header_id|>

Answer the following questions:
1. The day before two days after the day before tomorrow is Saturday. What day is it today?
2. What is the square root of 169?
3. Solve the equation 3y = 6y + 11 and find y.
4. There are two ducks in front of a duck, two ducks behind a duck, and a duck in the middle. How many ducks are there?
5. How many days does it take to travel from New York City to London by plane, assuming non-stop flights and average speeds?
6. What are the products of the chemical reaction between salicylic acid and acetic anhydride?
7. If five cats can catch five mice in five minutes, how long will it take one cat to catch one mouse?
8. Create a JS program that prints the first 100 Fibonacci numbers.  <|eot_id|><|start_header_id|>assistant<|end_header_id|>


'
[1720021651] input tokens: [ '<|start_header_id|>':128006, 'user':882, '<|end_header_id|>':128007, '':271, '<|begin_of_text|>':128000, '<|start_header_id|>':128006, 'system':9125, '<|end_header_id|>':128007, '':271, 'Role':9207, ' and':323, ' Purpose':30145, ':':25, ' You':1472, ' are':527, ' Alice':30505, ',':11, ' a':264, ' large':3544, ' language':4221, ' model':1646, '.':13, ' Your':4718, ' purpose':7580, ' is':374, ' to':311, ' assist':7945, ' users':3932, ' by':555, ' providing':8405, ' information':2038, ',':11, ' answering':36864, ' questions':4860, ',':11, ' and':323, ' engaging':23387, ' in':304, ' meaningful':23222, ' conversations':21633, ' based':3196, ' on':389, ' the':279, ' data':828, ' you':499, ' were':1051, ' trained':16572, ' on':389, '.':13, ' Behavior':27773, ' and':323, ' Tone':68004, ':':25, ' ':220, ' Be':2893, ' informative':39319, ',':11, ' engaging':23387, ',':11, ' and':323, ' respectful':49150, '.':13, ' Maintain':87477, ' a':264, ' neutral':21277, ' and':323, ' unbiased':74315, ' tone':16630, '.':13, ' Ensure':30379, ' that':430, ' responses':14847, ' are':527, ' clear':2867, ' and':323, ' concise':64694, '.':13, ' Cap':8171, 'abilities':8623, ':':25, ' Use':5560, ' your':701, ' training':4967, ' data':828, ' to':311, ' provide':3493, ' accurate':13687, ' and':323, ' relevant':9959, ' information':2038, '.':13, ' Explain':83017, ' complex':6485, ' concepts':19476, ' in':304, ' an':459, ' easy':4228, '-to':4791, '-under':72207, 'stand':2752, ' manner':11827, '.Pro':7919, 'vide':20013, ' sources':8336, ' when':994, ' referencing':57616, ' specific':3230, ' information':2038, ' or':477, ' data':828, '.':13, ' Output':9442, ' Formatting':90688, ':':25, ' Use':5560, ' this':420, ' formatting':37666, ' for':369, ' code':2082, ':':25, ' ```':55375, 'language':11789, ' /':611, 'n':77, '```':74694, '<|eot_id|>':128009, '<|start_header_id|>':128006, 'user':882, '<|end_header_id|>':128007, '':271, 'Answer':16533, ' the':279, ' following':2768, ' questions':4860, ':':512, '1':16, '.':13, ' The':578, ' day':1938, ' before':1603, ' two':1403, ' days':2919, ' after':1306, ' the':279, ' day':1938, ' before':1603, ' tomorrow':16986, ' is':374, ' Saturday':7884, '.':13, ' What':3639, ' day':1938, ' is':374, ' it':433, ' today':3432, '?':5380, '2':17, '.':13, ' What':3639, ' is':374, ' the':279, ' square':9518, ' root':3789, ' of':315, ' ':220, '169':11739, '?':5380, '3':18, '.':13, ' Solve':64384, ' the':279, ' equation':24524, ' ':220, '3':18, 'y':88, ' =':284, ' ':220, '6':21, 'y':88, ' +':489, ' ':220, '11':806, ' and':323, ' find':1505, ' y':379, '.':627, '4':19, '.':13, ' There':2684, ' are':527, ' two':1403, ' ducks':78878, ' in':304, ' front':4156, ' of':315, ' a':264, ' duck':37085, ',':11, ' two':1403, ' ducks':78878, ' behind':4920, ' a':264, ' duck':37085, ',':11, ' and':323, ' a':264, ' duck':37085, ' in':304, ' the':279, ' middle':6278, '.':13, ' How':2650, ' many':1690, ' ducks':78878, ' are':527, ' there':1070, '?':5380, '5':20, '.':13, ' How':2650, ' many':1690, ' days':2919, ' does':1587, ' it':433, ' take':1935, ' to':311, ' travel':5944, ' from':505, ' New':1561, ' York':4356, ' City':4409, ' to':311, ' London':7295, ' by':555, ' plane':11277, ',':11, ' assuming':26619, ' non':2536, '-stop':42311, ' flights':25952, ' and':323, ' average':5578, ' speeds':25753, '?':5380, '6':21, '.':13, ' What':3639, ' are':527, ' the':279, ' products':3956, ' of':315, ' the':279, ' chemical':11742, ' reaction':13010, ' between':1990, ' sal':4371, 'icy':2912, 'lic':416, ' acid':13935, ' and':323, ' ac':1645, 'etic':5411, ' an':459, 'hy':8671, 'd':67, 'ride':1425, '?':5380, '7':22, '.':13, ' If':1442, ' five':4330, ' cats':19987, ' can':649, ' catch':2339, ' five':4330, ' mice':24548, ' in':304, ' five':4330, ' minutes':4520, ',':11, ' how':1268, ' long':1317, ' will':690, ' it':433, ' take':1935, ' one':832, ' cat':8415, ' to':311, ' catch':2339, ' one':832, ' mouse':8814, '?':5380, '8':23, '.':13, ' Create':4324, ' a':264, ' JS':12438, ' program':2068, ' that':430, ' prints':24370, ' the':279, ' first':1176, ' ':220, '100':1041, ' Fibonacci':80783, ' numbers':5219, '.':13, '  ':256, '<|eot_id|>':128009, '<|start_header_id|>':128006, 'assistant':78191, '<|end_header_id|>':128007, '<|eot_id|>':128009, '<|start_header_id|>':128006, 'assistant':78191, '<|end_header_id|>':128007, '':271 ]
[1720021651] n_remain: -318
[1720021651] embd_inp.size(): 327, n_consumed: 6

**Comment by ngxson** [comment] 2024-07-03 15:58
Maybe you're using outdated version. Check on my side:

```
make llama-cli -j && ./llama-cli -m ../models/Meta-Llama-3-8B-Instruct-abliterated-v3_q4.gguf -cnv --in-prefix "" -c 1024 -p "You are AI"

main.log:

[1720022194] eval: [ '<|begin_of_text|>':128000, 'You':2675, ' are':527, ' AI':15592 ]
```

**Comment by ngxson** [comment] 2024-07-03 16:02
> ../llama.cpp/llama-cli --model ../../models/Meta-Llama-3-8B-Instruct_Q5_K_S.gguf --n-gpu-layers 30 -cnv --interactive --interactive-first --simple-io -b 2048 -n -1 -e --ctx_size 0 --temp 0.5 --top_k 10 --multiline-input --repeat_penalty 1.12 -t 8 --in-prefix-bos --in-prefix "" --log-enable --logdir ./ --no-display-prompt

Again, entering all options at the same time will only waste your time & my time to pinpoint the problem. I can't see no where the prompt file is specified, but the prompt magically appears in the log you sent:

> Role and Purpose: You are Alice, a large language model. Your purpose is to assist users by providing information, answering questions, and engaging in meaningful conversations based on the data you were trained on.

You probably have all the chat tokens pre-formatted inside your prompt.

**Comment by dspasyuk** [comment] 2024-07-03 16:07
@ngxson yes, this is entire prompt, I did not specify system prompt with -p option to avoid any formatting issue that might arise with that:

'<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Role and Purpose: You are Alice, a large language model. Your purpose is to assist users by providing information, answering questions, and engaging in meaningful conversations based on the data you were trained on. Behavior and Tone: Be informative, engaging, and respectful. Maintain a neutral and unbiased tone. Ensure that responses are clear and concise. Capabilities: Use your training data to provide accurate and relevant information. Explain complex concepts in an easy-to-understand manner.Provide sources when referencing specific information or data. Output Formatting: Use this formatting for code: language /n<|eot_id|><|start_header_id|>user<|end_header_id|>

Answer the following questions:

    The day before two days after the day before tomorrow is Saturday. What day is it today?
    What is the square root of 169?
    Solve the equation 3y = 6y + 11 and find y.
    There are two ducks in front of a duck, two ducks behind a duck, and a duck in the middle. How many ducks are there?
    How many days does it take to travel from New York City to London by plane, assuming non-stop flights and average speeds?
    What are the products of the chemical reaction between salicylic acid and acetic anhydride?
    If five cats can catch five mice in five minutes, how long will it take one cat to catch one mouse?
    Create a JS program that prints the first 100 Fibonacci numbers. <|eot_id|><|start_header_id|>assistant<|end_header_id|>

**Comment by dspasyuk** [comment] 2024-07-03 16:20
Yep, confirm, It looks the prefix issues was related to version 3225 that I was using before, today version does not have that issue I have overwritten the default prompt successfully. I will keep on digging. Thank you for your help @ngxson

**Comment by ngxson** [comment] 2024-07-03 16:23
I think that’s already obvious: you added these tokens on your prompt, so the program just do exactly what you ask it to do?

In anyway, I don’t think there are any bug here. This is quite wasting time for me so I will close this thread.

**Closed by ngxson** 2024-07-03 16:23 UTC
Labels: bug-unconfirmed, medium severity

**Comment by dspasyuk** [comment] 2024-07-03 19:56
The prefix was not an issue for me, the prefix issue became an issue when I was trying to track the issue with templates and stalled output generation. Reliability of output is the problem.
