### ISSUE TITLE
Using make to build llama.cpp:common/common.cpp:1108:55: error: expected primary-expression before ')' token  1108 |     fprintf(stream, "build_number: %d\n", BUILD_NUMBER);

### ISSUE THREAD

**Issue by OuXiao514** [ggerganov/llama.cpp#3673] opened 2023-10-19 03:49 UTC
D:/LLM/llama.cpp-master $ make
I llama.cpp build info:
I UNAME_S:   Windows_NT
I UNAME_P:   unknown
I UNAME_M:   x86_64
I CFLAGS:    -I. -Icommon -D_XOPEN_SOURCE=600 -DNDEBUG -DGGML_USE_K_QUANTS  -std=c11   -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Werror=implicit-function-declaration -Wdouble-promotion -march=native -mtune=native -Xassembler -muse-unaligned-vector-move
I CXXFLAGS:  -I. -Icommon -D_XOPEN_SOURCE=600 -DNDEBUG -DGGML_USE_K_QUANTS  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -Xassembler -muse-unaligned-vector-move  -Wno-array-bounds -Wno-format-truncation -Wextra-semi -march=native -mtune=native
I NVCCFLAGS:  -I. -Icommon -D_XOPEN_SOURCE=600 -DNDEBUG -DGGML_USE_K_QUANTS  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -Xassembler -muse-unaligned-vector-move    -Wno-pedantic -Xcompiler "-Wno-array-bounds -Wno-format-truncation -Wextra-semi -march=native -mtune=native "
I LDFLAGS:
I CC:        cc (GCC) 13.2.0
I CXX:       g++ (GCC) 13.2.0

g++ -I. -Icommon -D_XOPEN_SOURCE=600 -DNDEBUG -DGGML_USE_K_QUANTS  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -Xassembler -muse-unaligned-vector-move  -Wno-array-bounds -Wno-format-truncation -Wextra-semi -march=native -mtune=native  -c common/common.cpp -o common.o
common/common.cpp: In function 'void dump_non_result_info_yaml(FILE*, const gpt_params&, const llama_context*, const std::string&, const std::vector<int>&, const char*)':
common/common.cpp:1108:55: error: expected primary-expression before ')' token
 1108 |     fprintf(stream, "build_number: %d\n", BUILD_NUMBER);
      |                                                       ^
make: *** [Makefile:551: common.o] Error 1

**Comment by OuXiao514** [comment] 2023-10-19 04:51
When I use cmake:
D:\LLM\llama.cpp-master\build>cmake --build . --config Release
适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa

  Checking Build System
  Building Custom Rule D:/LLM/llama.cpp-master/CMakeLists.txt
  ggml.c
  ggml-alloc.c
  ggml-backend.c
  k_quants.c
  正在生成代码...
  ggml.vcxproj -> D:\LLM\llama.cpp-master\build\ggml.dir\Release\ggml.lib
  Building Custom Rule D:/LLM/llama.cpp-master/CMakeLists.txt
  llama.cpp
D:\LLM\llama.cpp-master\llama.cpp(1055,31): warning C4305: “初始化”: 从“double”到“float”截断 [D:\LLM\llama.cpp-master\build\llama.vcxproj]
D:\LLM\llama.cpp-master\llama.cpp(1205,40): warning C4566: 由通用字符名称“\u0120”表示的字符不能在当前代码页(936)中表示出来 [D:\LLM\llama.cpp-master\build\llama.vcxproj]
D:\LLM\llama.cpp-master\llama.cpp(1206,40): warning C4566: 由通用字符名称“\u010A”表示的字符不能在当前代码页(936)中表示出来 [D:\LLM\llama.cpp-master\build\llama.vcxproj]
D:\LLM\llama.cpp-master\llama.cpp(1207,40): warning C4566: 由通用字符名称“\u0120”表示的字符不能在当前代码页(936)中表示出来 [D:\LLM\llama.cpp-master\build\llama.vcxproj]
D:\LLM\llama.cpp-master\llama.cpp(1208,40): warning C4566: 由通用字符名称“\u010A”表示的字符不能在当前代码页(936)中表示出来 [D:\LLM\llama.cpp-master\build\llama.vcxproj]
D:\LLM\llama.cpp-master\llama.cpp(2238,60): warning C4566: 由通用字符名称“\u010A”表示的字符不能在当前代码页(936)中表示出来 [D:\LLM\llama.cpp-master\build\llama.vcxproj]
D:\LLM\llama.cpp-master\llama.cpp(9724,28): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型 [D:\LLM\llama.cpp-master\build\llama.vcxproj]
D:\LLM\llama.cpp-master\llama.cpp(9754,28): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型 [D:\LLM\llama.cpp-master\build\llama.vcxproj]
  llama.vcxproj -> D:\LLM\llama.cpp-master\build\Release\llama.lib
  Building Custom Rule D:/LLM/llama.cpp-master/common/CMakeLists.txt
  common.cpp
D:\LLM\llama.cpp-master\common\common.cpp(1108,55): error C2059: 语法错误:“)” [D:\LLM\llama.cpp-master\build\common\common.vcxproj]
  sampling.cpp
  console.cpp
D:\LLM\llama.cpp-master\common\console.cpp(253,30): warning C4267: “初始化”: 从“size_t”转换到“DWORD”，可能丢失数据 [D:\LLM\llama.cpp-master\build\common\common.vcxproj]
D:\LLM\llama.cpp-master\common\console.cpp(407,28): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据 [D:\LLM\llama.cpp-master\build\common\common.vcxproj]
  grammar-parser.cpp
  train.cpp
  正在生成代码...

**Comment by shibe2** [comment] 2023-10-19 08:46
There is probably a bug in generation of build-info.h when not building from Git tree. I have to manually edit it after running CMake.

**Comment by OuXiao514** [comment] 2023-10-19 09:53
How to edit build-info.h?

**Comment by OuXiao514** [comment] 2023-10-19 10:23
I find!
#ifndef BUILD_INFO_H
#define BUILD_INFO_H

#define BUILD_NUMBER 1399
#define BUILD_COMMIT "004797f"
#define BUILD_COMPILER "MSVC 19.37.32822.0"
#define BUILD_TARGET "x64"

#endif // BUILD_INFO_H

**Comment by staviq** [comment] 2023-10-19 12:18
Possible duplicate of #3670

**Comment by shibe2** [comment] 2023-10-20 06:43
@OuXiao514 Have you managed to build it? What was the problem?

**Comment by OuXiao514** [comment] 2023-10-20 10:38
When I editor build-info.h, It is successful to build the project. But it has some warning. such as:
 D:\LLM\llama.cpp-master\.\llama.cpp(1055,31): warning C4305: “初始化”: 从“double”到“float”截断 [D:\LLM\llama.cpp-master\build\tests\test-llama-grammar.vcxproj]
D:\LLM\llama.cpp-master\.\llama.cpp(1205,40): warning C4566: 由通用字符名称“\u0120”表示的字符不能在当前代码页(936)中表示出来 [D:\LLM\llama.cpp-master\build\tests\test-llama-grammar.vcxproj]
D:\LLM\llama.cpp-master\.\llama.cpp(1206,40): warning C4566: 由通用字符名称“\u010A”表示的字符不能在当前代码页(936)中表示出来 [D:\LLM\llama.cpp-master\build\tests\test-llama-grammar.vcxproj]
D:\LLM\llama.cpp-master\.\llama.cpp(1207,40): warning C4566: 由通用字符名称“\u0120”表示的字符不能在当前代码页(936)中表示出来 [D:\LLM\llama.cpp-master\build\tests\test-llama-grammar.vcxproj]

**Comment by shibe2** [comment] 2023-10-20 12:10
Then we can indeed consider it a duplicate of #3670.

**Closed by shibe2** 2023-10-20 12:10 UTC
