### ISSUE TITLE
Failing to convert the new PHI-3 models.

### ISSUE THREAD

**Issue by 0wwafa** [ggerganov/llama.cpp#8259] opened 2024-07-02 16:49 UTC
```
INFO:hf-to-gguf:Loading model: Phi-3-mini-128k-instruct
INFO:gguf.gguf_writer:gguf: This GGUF file is for Little Endian only
INFO:hf-to-gguf:Set model parameters
Traceback (most recent call last):
  File "/content/llama.cpp/convert-hf-to-gguf.py", line 3263, in <module>
    main()
  File "/content/llama.cpp/convert-hf-to-gguf.py", line 3244, in main
    model_instance.set_gguf_parameters()
  File "/content/llama.cpp/convert-hf-to-gguf.py", line 1950, in set_gguf_parameters
    raise NotImplementedError(f'The rope scaling type {rope_scaling_type} is not supported yet')
NotImplementedError: The rope scaling type longrope is not supported yet
```

**Comment by duynt575** [comment] 2024-07-02 21:57
The output clearly stated 'not supported yet', you should stop submitting issue every time.

**Comment by 0wwafa** [comment] 2024-07-03 06:42
well, I think phi-3 models deserve to be supported in full. they are smashing the leaderboard at the moment...

**Comment by duynt575** [comment] 2024-07-03 07:47
If you really think that then fork the repo and do it yourself. Stop demanding ffs!

**Comment by HanClinto** [comment] 2024-07-03 15:53
Relevant work on phi3 is being done in a few different places, but perhaps most centrally in #7705 if you're looking for a place to jump in.

Thank you!

**Comment by HanClinto** [comment] 2024-07-03 15:56
Duplicate of #8241, #7922, #6849. Please refer to #6849 or #7705 to contribute. Opening new issues is only fragmenting the discussion. 

Thank you.

**Closed by HanClinto** 2024-07-03 15:56 UTC
