### ISSUE TITLE
Add support for stopping words [Automation]

### ISSUE THREAD

**Issue by appvoid** [ggerganov/llama.cpp#726] opened 2023-04-02 23:45 UTC
A stopping criteria or "stop sequence" would be highly appreciated here. These models are already pretty for information retrieval but for automating stuff be it maybe some hacky way to execute code or simply automate textual tasks is impossible. You can just use the model and expect it to work everytime with every input. And even if is the case, your won't last long before your prompt needs a modification.

Will you at least include that feature some day? I'm mot a cpp expert so I'm not sure how difficult would be this to implement.

**Comment by prusnak** [comment] 2023-04-03 00:20
Duplicate of https://github.com/ggerganov/llama.cpp/issues/57

**Comment by appvoid** [comment] 2023-04-10 01:21
You didn't get me. I'm looking for a way to automate stuff which I can't just do with that feature. For example, let's say you use a prompt to automate replies for emails.

prompt:
`The following message is responded in a formal way.
message: *******
output: <something similar to my expected response>`

Finally, when it generates the answer, I'm not able to stop the process, feed a different prompt instead of using the original or anything to properly automate that task which pretty much renders it useless unless you use llama models as sometimes factual chatbots.

**Comment by sergedc** [comment] 2023-04-18 01:45
if (!input_noecho) {
            for (auto id : embd) {
                printf("%s", llama_token_to_str(ctx, id));
                csvoutputline += llama_token_to_str(ctx, id);
                if((int) embd.size() == 1 && (strcmp(llama_token_to_str(ctx, id), "#") == 0 || strcmp(llama_token_to_str(ctx, id), "##") == 0 || strcmp(llama_token_to_str(ctx, id), "###") == 0)) {
                    exit(0);
                }

            }

in main.cpp: look for if (!input_noecho) 
My code would force exit if the AI generates # or ## or ###

Really you just need to add the if statement and get your condition right. 

You cannot code c++? No worries, in 2023, only geniuses like @ggerganov need to know how to code. For everyone else, use ChatGPT, give him the code, tell him what you want and copy / paste.
Ho my no, this makes me think of the movie Idiocracy. More relevant than ever.

**Closed** 2023-07-28 19:46 UTC
