### ISSUE TITLE
python bindings?

### ISSUE THREAD

**Issue by bryanhpchiang** [ggerganov/llama.cpp#82] opened 2023-03-13 07:00 UTC

**Comment by MarkSchmidty** [comment] 2023-03-14 05:50
Python Bindings for llama.cpp: https://pypi.org/project/llamacpp/0.1.3/ (not mine, just found them)

**Comment by shaunabanana** [comment] 2023-03-15 13:16
As a temporary work-around before an "official" binding is available, I've written a quick script to call the llama.cpp executable that supports streaming and interactive mode: [https://github.com/shaunabanana/llama.py](https://github.com/shaunabanana/llama.py)

**Comment by aratic** [comment] 2023-03-15 16:21
> Python Bindings for llama.cpp: https://pypi.org/project/llamacpp/0.1.3/ (not mine, just found them)

looks promising on description, will try try and feedback

**Comment by bryanhpchiang** [comment] 2023-03-15 20:47
sweet will give it a shot

**Comment by seemanne** [comment] 2023-03-17 21:04
I hacked something together tonight on this. Its python-cpp bindings for the model directly (allowing you to call `model.generate()` from python and getting the string in returned. It doesn't support setting parameters within python yet (working on it), but it is model agnostic so you can load whatever ggml supports.

Merging it would however require splitting some parts of the code out of main.cpp which @ggerganov has argued against IIRc.

https://github.com/seemanne/llamacpypy

**Comment by aratic** [comment] 2023-03-18 05:21
@seemanne u did what I want, dude, easier to expose or integrate with web or chat, appreciate and will give it a try

**Comment by LostRuins** [comment] 2023-03-18 16:52
I wrote my own ctypes bindings and wrapped it an a KoboldAI compatible REST API.

https://github.com/LostRuins/llama-for-kobold

**Comment by abetlen** [comment] 2023-03-22 11:03
If anyone's just looking for python bindings I put together [`llama.py`](https://gist.github.com/abetlen/2b90e5f153f6efd00931d098de5c73ce) which uses ctypes to expose the current C API.

To use it you have to first build `llama.cpp` as a shared library and then put the shared library in the same directory as the llama.py file. 

On Linux for example, to build the shared library, update the `Makefile` to add a new target for `libllama.so`
```Makefile
libllama.so: llama.o ggml.o
	$(CXX) $(CXXFLAGS) -shared -fPIC -o libllama.so llama.o ggml.o $(LDFLAGS)
```
Then run `make libllama.so` to generate the library.

**Comment by Piezoid** [comment] 2023-03-22 21:49
I also found these bindings https://github.com/PotatoSpudowski/fastLLaMa

Some feature suggestions, mostly about low level capabilities:
- Accessing the output classifier activations from python, enabling sampling and quantitative evaluation from python, 
- Managing k/v state with its own python object, allowing to swap them in and out.
- Array view on embedding and the possibility to bypass `ggml_get_rows` for feeding back embedding crafted by hand.

**Comment by DrBenjamin** [comment] 2023-03-27 08:58
> EDIT: I've adapted the single-file bindings into a pip-installable package (will build llama.cpp on install) called [llama-cpp-python](https://github.com/abetlen/llama-cpp-python)
> 
> If anyone's just looking for python bindings I put together [`llama.py`](https://gist.github.com/abetlen/2b90e5f153f6efd00931d098de5c73ce) which uses ctypes to expose the current C API.
> 
> To use it you have to first build `llama.cpp` as a shared library and then put the shared library in the same directory as the llama.py file.
> 
> On Linux for example, to build the shared library, update the `Makefile` to add a new target for `libllama.so`
> 
> ```makefile
> libllama.so: llama.o ggml.o
> 	$(CXX) $(CXXFLAGS) -shared -fPIC -o libllama.so llama.o ggml.o $(LDFLAGS)
> ```
> 
> Then run `make libllama.so` to generate the library.

Having issues with both variants on a M1 Mac:
from llama_cpp import Llama
produces this error:
 
zsh: illegal hardware instruction

The python bindings approach (after building the shared library) produces:
libllama.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

**Comment by PotatoSpudowski** [comment] 2023-04-17 17:49
> I also found these bindings https://github.com/PotatoSpudowski/fastLLaMa
> 
> Some feature suggestions, mostly about low level capabilities:
> 
> * Accessing the output classifier activations from python, enabling sampling and quantitative evaluation from python,
> * Managing k/v state with its own python object, allowing to swap them in and out.
> * Array view on embedding and the possibility to bypass `ggml_get_rows` for feeding back embedding crafted by hand.

We have added most of these suggestion in the latest fastLLaMa update 👀

**Comment by dmahurin** [comment] 2023-05-17 12:47
As #1156  is closed ad duplicate of this issue, I am bringing the discussion here about the creation of an official python binding in the llama.cpp repository (which I now assume the the objective of this issue.)

The current external python bindings seem to be:
- llama-cpp-python
- llamacpp
- pyllamacpp
- llamacpypy
- fastllama

But none really stand out as a candidate to be merged into llama.cpp.

My proposal is to model the llama.cpp bindings after rwkv.cpp by @saharNooby (bert.cpp also follows a similar path).

- Assume llama.cpp is built as shared library (built with BUILD_SHARED_LIBS=ON )
- Create basic python bindings that just expose functions in the shared library as is
- (optional) Create a higher level model that that builds on the basic bindings
- Change the examples to be written in python, rather than bash

We could keep the following in mind for the basic binding:
- completeness - should be a complete binding, aligning to the llama.cpp interface
- simplicity - relatively strait-forward, easy to understand implementation
- easily to maintain

Any suggestion on which of the current external python bindings could be considered a good start for eventual merge into llama.cpp?

**Comment by dmahurin** [comment] 2023-05-17 12:59
> If anyone's just looking for python bindings I put together [llama.py](https://gist.github.com/abetlen/2b90e5f153f6efd00931d098de5c73ce) which uses ctypes to expose the current C API.

@abetlen , could this single file implementation be a starting point?

**Comment by dmahurin** [comment] 2023-05-17 16:53
Hi @seemanne, the purpose is not to replace bash.  The purpose is to widen the development community.  Like it or not, Python is a very common language in AI development.

I do not think having supported python code would put any burden on cpp developers. Again, reference rwkv.cpp and bert.cpp.  The python support in rwkv.cpp for example comes in the form of two python files.

As mentioned, there are 5 independent python bindings for llama.cpp.   Unifying at least the base python binding would help to focus related python llama.cpp development.

For me, this started because I did try the one mentioned in the README, it did not work, and I tried several of the others. They did not work either.  This is quite different than my experience with rwkv.cpp, which just worked. Since the python is used in the project, it will stay current.  Does this require a small amount of python knowledge in this project.  Yes.  But isn't that ok?

**Comment by dmahurin** [comment] 2023-05-17 17:01
Hi @abetlen, is there much differences between the single file llama.py you posted, and llama.py ctype bindings in llama-cpp-python?

**Comment by dmahurin** [comment] 2023-06-01 17:19
@abetlen, perhaps you saw that I created pull request #1660 to add low level python bindings from llama-cpp-python.

The PR puts llama_cpp.py and low level examples in the examples/ folder.

There was a bit of filtering and some squashing to get clean history for the low level commits. For now I excluded the multi char change, mainly because it created a dependency on another file, util.py. (and the change looks more complex than I would expect).

Any comments on the approach of the PR?

**Closed** 2023-07-28 19:29 UTC
Labels: enhancement
