### ISSUE TITLE
a quick embedding question 

### ISSUE THREAD

**Issue by xvolica** [ggerganov/llama.cpp#3189] opened 2023-09-15 09:46 UTC
I was very excited to find out that there is a embed function to convert a long sentence to embedding. But I didn't see the api explanation, I want to know that where does the embedding come from at llama2 model? 
What more, I want to know that is there any different between using chat and embedding, what kind of prompt will generate a better embedding? Is there any issue to support that?

**Comment by staviq** [comment] 2023-09-15 16:16
I suggest moving this to Discussions as this is not a bug.

**Closed** 2023-09-18 03:22 UTC
