### ISSUE TITLE
Server stop working after recent refactor on Windows

### ISSUE THREAD

**Issue by sorasoras** [ggerganov/llama.cpp#5963] opened 2024-03-09 14:25 UTC
latest branch
server stop working after recently refactor.
I couldn't run server.exe on my Windows build Rocm

```
PS W:\git\llama.cpp\AVX2\bin> .\server.exe -h
PS W:\git\llama.cpp\AVX2\bin> .\server.exe
PS W:\git\llama.cpp\AVX2\bin>
```
compile with

` cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DLLAMA_HIPBLAS=ON  -DCMAKE_C_COMPILER="C:/Program Files/AMD/ROCm/5.7/bin/clang.exe" -DCMAKE_CXX_COMPILER="C:/Program Files/AMD/ROCm/5.7/bin/clang++.exe" -DAMDGPU_TARGETS="gfx1100;gfx1030;gfx1031"`

**Comment by characharm** [comment] 2024-03-09 14:47
The issue is not only with ROCm but also with Vulkan and even AVX2.

**Comment by FredericoPerimLopes** [comment] 2024-03-09 14:49
I'm also unable to load server on windows.

**Comment by ggerganov** [comment] 2024-03-09 15:03
Seems like a Windows-related problem, so unfortunately I won't be able to help with that.

Could you try to pin-point the exact commit after which it stops working?

**Comment by sorasoras** [comment] 2024-03-09 15:08
> Seems like a Windows-related problem, so unfortunately I won't be able to help with that.
> 
> Could you try to pin-point the exact commit after which it stops working?

https://github.com/ggerganov/llama.cpp/pull/5882
this one but this is a huge pr

**Comment by slaren** [comment] 2024-03-09 15:11
This happens because `ggml_time_us` is being called (in `server_metrics`) before `ggml_time_init`, which results in a division by zero as `timer_freq` is zero.

**Comment by ggerganov** [comment] 2024-03-09 15:34
Should be fixed now

**Closed** 2024-03-09 15:34 UTC
Labels: bug-unconfirmed

**Comment by phymbert** [comment] 2024-03-09 19:20
Thanks @ggerganov is it worth the effort to add a ci workflow for server tests on Windows ? if yes, I will give it a try next week

**Comment by ggerganov** [comment] 2024-03-09 19:24
Yes, would be useful to have a Windows run
