### ISSUE TITLE
[Feature request] Support for "Falcon" model

### ISSUE THREAD

**Issue by hfassold** [ggerganov/llama.cpp#1650] opened 2023-05-30 09:31 UTC
"Falcon" is a new Large Language Model which seems to be better than Llama.
See https://falconllm.tii.ae/ and
https://iamgeekydude.com/2023/05/28/falcon-llm-the-40-billion-parameters-llm/ and
https://www.marktechpost.com/2023/05/28/technology-innovation-institute-open-sourced-falcon-llms-a-new-ai-model-that-uses-only-75-percent-of-gpt-3s-training-compute-40-percent-of-chinchillas-and-80-percent-of-palm-62b/

Actually, it is the best open-source model currently available according to the authors.

Model (for Huggingface Transformers library) with 40B and 7B parameters is available at :
https://huggingface.co/tiiuae/falcon-40b

Would be great if it would be supported also in llama.cpp.
Note it uses some novel layers (FlashAttention, Multiquery).

**Comment by Green-Sky** [comment] 2023-05-30 09:52
duplicate of #1602

**Closed** 2023-05-30 11:34 UTC
Labels: duplicate
