### ISSUE TITLE
Docker fails due to missing tqdm

### ISSUE THREAD

**Issue by Technetium1** [ggerganov/llama.cpp#310] opened 2023-03-19 23:02 UTC
```
docker run -v /llama/models:/models ghcr.io/ggerganov/llama.cpp:full --all-in-one "/models/" 65B
```
```
Unable to find image 'ghcr.io/ggerganov/llama.cpp:full' locally
full: Pulling from ggerganov/llama.cpp
2ab09b027e7f: Pull complete
abc582ff34c3: Pull complete
474c54188cc5: Pull complete
90dde168a635: Pull complete
4baa98a3bbd6: Pull complete
40709b48f1dd: Pull complete
Digest: sha256:0e26a42b34ad42f285a4327fbe099674137b119e6efea07345a7c17ab8a4b13e
Status: Downloaded newer image for ghcr.io/ggerganov/llama.cpp:full
Downloading model...
Traceback (most recent call last):
  File "/app/./download-pth.py", line 3, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

**Comment by Technetium1** [comment] 2023-03-19 23:05
Looks like it should be added here:

https://github.com/ggerganov/llama.cpp/blob/da5303c1ea68aa19db829c634f1e10d08d409680/.devops/full.Dockerfile#L9

---

also see https://github.com/ggerganov/llama.cpp/pull/308 ?

**Comment by sw** [comment] 2023-03-20 09:01
Duplicate of #289, fixed in master

**Closed by sw** 2023-03-20 09:01 UTC
Labels: duplicate
