### ISSUE TITLE
SYCL NVidia build failing

### ISSUE THREAD

**Issue by AidanBeltonS** [ggerganov/llama.cpp#6026] opened 2024-03-12 17:54 UTC
NVidia SYCL build failing due to multiple GPUs support PR.
This comes from https://github.com/ggerganov/llama.cpp/pull/5806/files#diff-6af12449fa63d10882b68b8230ff092164a786e01683813a005267630ab9c0b2R3330. 
CUDA versions translate the the SM number, so for SM80 the major version is 8.

I believe we should refrain from using versions if possible in the SYCL backend as it is less backend agnostic.

### Steps to reproduce:
`$./bin/test-backend-ops -b SYCL0`
```
ggml_backend_register: registered backend CPU
terminate called after throwing an instance of 'sycl::_V1::invalid_parameter_error'
  what():  DeviceList is empty. -30 (PI_ERROR_INVALID_VALUE)
Aborted
```

**Comment by AidanBeltonS** [comment] 2024-03-12 17:54
PR introducing bug: https://github.com/ggerganov/llama.cpp/pull/5806

**Comment by NeoZhangJianyu** [comment] 2024-03-13 13:29
https://github.com/ggerganov/llama.cpp/pull/5806 is already reverted.
Please check again!

**Comment by NeoZhangJianyu** [comment] 2024-03-13 14:24
I guess the parameter "SYCL0" is the cause.
SYCL0 maybe not the GPU device.
It's better not set any parameter, the UT case will detect the GPU devices.

Please run following cmd to list the SYCL device:
```
source /opt/intel/oneapi/setvars.sh
./build/bin/ls-sycl-device
```

**Comment by AidanBeltonS** [comment] 2024-03-13 14:50
> I guess the parameter "SYCL0" is the cause. SYCL0 maybe not the GPU device. It's better not set any parameter, the UT case will detect the GPU devices.
> 
> Please run following cmd to list the SYCL device:
> 
> ```
> source /opt/intel/oneapi/setvars.sh
> ./build/bin/ls-sycl-device
> ```

The problem is not tied to passing a specific device.
The device list passed to when attempting to construct the context is empty. This is because you require the major version == 1 to be added to the device list. This was introduced in PR5806 and remains in the code base.

The major version for an NVidia A100 is 8, the major version for an AMD MI210 is 90.
The version numbers are very much a backend specific value which I do not recommend using.
What are you trying to do with this query, I would like to help provide a suitable alternative?


FYI:
```
$ ./bin/ls-sycl-device
found 3 SYCL devices:
|ID| Name                                        |compute capability|Max compute units|Max work group|Max sub group|Global mem size|
|--|---------------------------------------------|------------------|-----------------|--------------|-------------|---------------|
| 0|                        NVIDIA A100-PCIE-40GB|               8.0|              108|          1024|           32|    42298834944|
| 1|               Intel(R) FPGA Emulation Device|               1.2|                2|      67108864|           64|    67117649920|
| 2|     Intel(R) Xeon(R) Gold 6326 CPU @ 2.90GHz|               3.0|                2|          8192|           64|    67117649920|
```

**Comment by NeoZhangJianyu** [comment] 2024-03-15 11:28
@AidanBeltonS if it's fixed, please close this issue.

**Closed** 2024-03-19 09:39 UTC
Labels: bug-unconfirmed
