### ISSUE TITLE
Stops generating after about 200 characters

### ISSUE THREAD

**Issue by somerandompiggo** [ggerganov/llama.cpp#212] opened 2023-03-16 19:53 UTC
I have tried modifying the -n (number of tokens to predict) but it always stops generating after the same amount of time. Is there any way to stop this happening? It seems to be intended behavior since it shows in the README screenshots

**Comment by lorenzopicoli** [comment] 2023-03-16 19:57
Probably duplicate of https://github.com/ggerganov/llama.cpp/issues/71

**Comment by somerandompiggo** [comment] 2023-03-16 19:59
Thanks, I didn't see that. I'll close the issue, but memory is not an issue as it says in that issue. I have 32GB of swap and 16GB of physical memory

**Closed** 2023-03-16 19:59 UTC
