### ISSUE TITLE
llama_model_load: error loading model: failed to allocate buffer

### ISSUE THREAD

**Issue by timschwartz** [ggerganov/llama.cpp#5057] opened 2024-01-21 03:26 UTC
Ever since commit e7e4df031b9e29d4b55a4e0b0295187f6b213db1 the server fails to load my models.

Before that commit the following command worked fine:

`RUSTICL_ENABLE=radeonsi OCL_ICD_VENDORS=rusticl.icd ./server -c 4096 --model /home/tim/projects/models/yi-34b-200k-dare-megamerge-v8.Q4_K_M.gguf -ngl 61` 

but now it outputs this:

```
ggml_opencl: selecting platform: 'rusticl'
ggml_opencl: selecting device: 'AMD Radeon RX 7900 XTX (gfx1100, LLVM 16.0.6, DRM 3.54, 6.5.0-5-amd64)'
ggml_opencl: device FP16 support: false
{"timestamp":1705807470,"level":"INFO","function":"main","line":2842,"message":"build info","build":1843,"commit":"e7e4df03"}
{"timestamp":1705807470,"level":"INFO","function":"main","line":2845,"message":"system info","n_threads":8,"n_threads_batch":-1,"total_threads":16,"system_info":"AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | "}

llama server listening at http://127.0.0.1:8080

{"timestamp":1705807470,"level":"INFO","function":"main","line":2949,"message":"HTTP server listening","port":"8080","hostname":"127.0.0.1"}
llama_model_loader: loaded meta data with 21 key-value pairs and 543 tensors from /home/tim/projects/models/yi-34b-200k-dare-megamerge-v8.Q4_K_M.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = brucethemoose_yi-34b-200k-dare-megame...
llama_model_loader: - kv   2:                       llama.context_length u32              = 200000
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 7168
llama_model_loader: - kv   4:                          llama.block_count u32              = 60
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 20480
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 56
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                       llama.rope.freq_base f32              = 5000000.000000
llama_model_loader: - kv  11:                          general.file_type u32              = 15
llama_model_loader: - kv  12:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,64002]   = ["<unk>", "<|startoftext|>", "<|endof...
llama_model_loader: - kv  14:                      tokenizer.ggml.scores arr[f32,64002]   = [-1000.000000, -1000.000000, -1000.00...
llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr[i32,64002]   = [3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  16:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  17:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  18:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  19:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  20:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  121 tensors
llama_model_loader: - type q4_K:  361 tensors
llama_model_loader: - type q6_K:   61 tensors
llm_load_vocab: mismatch in special tokens definition ( 500/64002 vs 5/64002 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 64002
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 200000
llm_load_print_meta: n_embd           = 7168
llm_load_print_meta: n_head           = 56
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 60
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 7
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 20480
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 5000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 200000
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 30B
llm_load_print_meta: model ftype      = Q4_K - Medium
llm_load_print_meta: model params     = 34.39 B
llm_load_print_meta: model size       = 19.24 GiB (4.81 BPW) 
llm_load_print_meta: general.name     = brucethemoose_yi-34b-200k-dare-megamerge-v8
llm_load_print_meta: BOS token        = 1 '<|startoftext|>'
llm_load_print_meta: EOS token        = 2 '<|endoftext|>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: PAD token        = 0 '<unk>'
llm_load_print_meta: LF token         = 315 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.41 MiB
ggml_backend_opencl_buffer_type_alloc_buffer: failed to allocate 19454.16 MiB
llama_model_load: error loading model: failed to allocate buffer
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '/home/tim/projects/models/yi-34b-200k-dare-megamerge-v8.Q4_K_M.gguf'
{"timestamp":1705807472,"level":"ERROR","function":"load_model","line":599,"message":"unable to load model","model":"/home/tim/projects/models/yi-34b-200k-dare-megamerge-v8.Q4_K_M.gguf"}
terminate called without an active exception

```

**Comment by hexbinoct** [comment] 2024-01-22 07:59
"gml_backend_opencl_buffer_type_alloc_buffer: failed to allocate 1048.51 MiB"

i was just running this on cell phone poco x3, snapdragon 732G , 6gb ram, works fine with ngl 15 but offloading to gpu doesnt help, the fastest inference is if ngl is 0, any idea why?

~/llama.cpp $ ./main -m ../storage/downloads/models/tinyllama-1.1b-chat-v1.0.Q8_0.gguf -ngl 23 -p "hello how are you?" -t 2
Log start
main: build = 1937 (504dc37b)
main: built with clang version 17.0.6 for aarch64-unknown-linux-android24
main: seed  = 1705910052
ggml_opencl: selecting platform: 'QUALCOMM Snapdragon(TM)'
ggml_opencl: selecting device: 'QUALCOMM Adreno(TM)'
ggml_opencl: device FP16 support: true
llama_model_loader: loaded meta data with 23 key-value pairs and 201 tensors from ../storage/downloads/models/tinyllama-1.1b-chat-v1.0.Q8_0.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str
     = llama
llama_model_loader: - kv   1:                               general.name str
     = tinyllama_tinyllama-1.1b-chat-v1.0
llama_model_loader: - kv   2:                       llama.context_length u32
     = 2048
llama_model_loader: - kv   3:                     llama.embedding_length u32
     = 2048
llama_model_loader: - kv   4:                          llama.block_count u32
     = 22
llama_model_loader: - kv   5:                  llama.feed_forward_length u32
     = 5632
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32
     = 64
llama_model_loader: - kv   7:                 llama.attention.head_count u32
     = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32
     = 4
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32
     = 0.000010
llama_model_loader: - kv  10:                       llama.rope.freq_base f32
     = 10000.000000
llama_model_loader: - kv  11:                          general.file_type u32
     = 7
llama_model_loader: - kv  12:                       tokenizer.ggml.model str
     = llama
llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  14:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  16:                      tokenizer.ggml.merges arr[str,61249]   = ["▁ t", "e r", "i n", "▁ a", "e n...
llama_model_loader: - kv  17:                tokenizer.ggml.bos_token_id u32
     = 1
llama_model_loader: - kv  18:                tokenizer.ggml.eos_token_id u32
     = 2
llama_model_loader: - kv  19:            tokenizer.ggml.unknown_token_id u32
     = 0
llama_model_loader: - kv  20:            tokenizer.ggml.padding_token_id u32
     = 2
llama_model_loader: - kv  21:                    tokenizer.chat_template str
     = {% for message in messages %}\n{% if m...
llama_model_loader: - kv  22:               general.quantization_version u32
     = 2
llama_model_loader: - type  f32:   45 tensors
llama_model_loader: - type q8_0:  156 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 2048
llm_load_print_meta: n_embd           = 2048
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 4
llm_load_print_meta: n_layer          = 22
llm_load_print_meta: n_rot            = 64
llm_load_print_meta: n_embd_head_k    = 64
llm_load_print_meta: n_embd_head_v    = 64
llm_load_print_meta: n_gqa            = 8
llm_load_print_meta: n_embd_k_gqa     = 256
llm_load_print_meta: n_embd_v_gqa     = 256
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 5632
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 2048
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 1B
llm_load_print_meta: model ftype      = Q8_0
llm_load_print_meta: model params     = 1.10 B
llm_load_print_meta: model size       = 1.09 GiB (8.50 BPW)
llm_load_print_meta: general.name     = tinyllama_tinyllama-1.1b-chat-v1.0
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: PAD token        = 2 '</s>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.15 MiB
ggml_backend_opencl_buffer_type_alloc_buffer: failed to allocate 1048.51 MiB
Segmentation fault
~/llama.cpp $

**Comment by timschwartz** [comment] 2024-01-27 00:51
Do you need any more information from me?

**Comment by slaren** [comment] 2024-01-27 14:34
@timschwartz the issue is clear, thanks for the report. After #2059 is merged we will have the ability to split the model weights into multiple buffers, and that should fix this issue.

**Comment by slaren** [comment] 2024-01-29 02:28
Can you test if #5181 fixes the issue?

**Comment by timschwartz** [comment] 2024-01-29 03:10
@slaren Yes, it works now thank you. It is also much faster.

**Closed** 2024-01-29 03:29 UTC
Labels: bug-unconfirmed
