### ISSUE TITLE
Bug: on AMD gpu, it offloads all the work to the CPU unless you specify --n-gpu-layers on the llama-cli command line

### ISSUE THREAD

**Issue by differentprogramming** [ggerganov/llama.cpp#8164] opened 2024-06-27 12:19 UTC
### What happened?

I spent days trying to figure out why it running a llama 3 instruct model was going super slow (about 3 tokens per second on fp16 and 5.6 on 8 bit) on an AMD MI50 32GB using rocBLAS for ROCm 6.1.2, using 0% GPU and 100% cpu even while using some vram.  I'm currently using release b3246

Finally I noticed that (for 8 bit) it said:
```

llm_load_tensors: offloading 0 repeating layers to GPU
llm_load_tensors: offloaded 0/33 layers to GPU
llm_load_tensors:        CPU buffer size =  8137.64 MiB

```

adding something to the command line like "--n-gpu-layers 100" changed it to
```
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors:      ROCm0 buffer size =  7605.33 MiB
llm_load_tensors:        CPU buffer size =   532.31 MiB
```
and it jumped from
```
llama_print_timings:        load time =    1955.34 ms
llama_print_timings:      sample time =      15.28 ms /   128 runs   (    0.12 ms per token,  8378.61 tokens per second)
llama_print_timings: prompt eval time =       0.00 ms /     0 tokens (    -nan ms per token,     -nan tokens per second)
llama_print_timings:        eval time =   23640.83 ms /   128 runs   (  184.69 ms per token,     5.41 tokens per second)
llama_print_timings:       total time =   23754.79 ms /   128 tokens
```

to
```
llama_print_timings:        load time =    2824.15 ms
llama_print_timings:      sample time =      12.57 ms /   128 runs   (    0.10 ms per token, 10182.98 tokens per second)
llama_print_timings: prompt eval time =       0.00 ms /     0 tokens (    -nan ms per token,     -nan tokens per second)
llama_print_timings:        eval time =    2469.71 ms /   128 runs   (   19.29 ms per token,    51.83 tokens per second)
llama_print_timings:       total time =    2566.10 ms /   128 tokens
```
The CPU usage went down from maxing out a bunch of cores to only using one.
The GPU usage went from 0% up to the 99%

16 bit didn't improve as much
it went from 
```
llama_print_timings:        load time =    2497.93 ms
llama_print_timings:      sample time =      15.75 ms /   128 runs   (    0.12 ms per token,  8126.47 tokens per second)
llama_print_timings: prompt eval time =       0.00 ms /     0 tokens (    -nan ms per token,     -nan tokens per second)
llama_print_timings:        eval time =   43228.83 ms /   128 runs   (  337.73 ms per token,     2.96 tokens per second)
llama_print_timings:       total time =   43344.71 ms /   128 tokens
```

to
```
llama_print_timings:        load time =    3937.74 ms
llama_print_timings:      sample time =      13.31 ms /   128 runs   (    0.10 ms per token,  9616.11 tokens per second)
llama_print_timings: prompt eval time =       0.00 ms /     0 tokens (    -nan ms per token,     -nan tokens per second)
llama_print_timings:        eval time =    8066.54 ms /   128 runs   (   63.02 ms per token,    15.87 tokens per second)
llama_print_timings:       total time =    8166.01 ms /   128 tokens
```

This is the command line I'm testing with

`build/bin/llama-cli -m ./models/llama3-8b-instruct/ggml-model-q8_0.gguf -n 128 --threads 12 --n-gpu-layers 100`

after building with

`HIPCXX="/opt/rocm-6.1.2/llvm/bin/clang" HIP_PATH="/opt/rocm-6.1.2"  cmake -S . -B build -DGGML_HIPBLAS=ON -DAMDGPU_TARGETS=gfx906 -DCMAKE_BUILD_TYPE=Release && cmake --build build  --config Release -- -j 12`

Yes I put the paths in manually.  It was just part of how I was messing around to see what's wrong

### Name and Version

version: 0 (unknown)
built with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu

The version string seems to be another bug, but I'm using the source from release b3246

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
llm_load_tensors: offloading 0 repeating layers to GPU
llm_load_tensors: offloaded 0/33 layers to GPU
llm_load_tensors:        CPU buffer size =  8137.64 MiB
```

**Comment by SteelPh0enix** [comment] 2024-06-27 15:55
isn't this just intended behavior? `--gpu-layers` is just 0 by default.

**Comment by shibe2** [comment] 2024-06-27 16:17
Not all the work is done on CPU. If you give it long prompt, it should use GPU.

**Comment by differentprogramming** [comment] 2024-06-27 17:44
None of the work is being done by the gpu, it runs exactly as fast as CPU build and gpu use stays at 0%.

The instructions should warn you that you have to tell it to put layers into the gpu to use the gpu.

**Comment by differentprogramming** [comment] 2024-06-27 17:45
Or just maybe, if you compile it to use a GPU the default should be to use it.

**Comment by differentprogramming** [comment] 2024-06-27 17:47
Note that there are other issues where people complained about these speeds and never figured out why.
I think they eventually got closed because people stopped talking.

**Comment by SteelPh0enix** [comment] 2024-06-27 18:39
I don't think enabling GPU offload by default is a good idea - partial offload can hurt performance too (we should not assume that the user will be able to automatically offload any model to GPU in full), and it can lead to more unexpected/unstable behaviors, leaving the CPU inference as default is a reasonable choice. 

One would say that discovering the GPU offload is "off" by default is a "rite of passage" for a new llama.cpp user. While i agree that there should maybe be a clear information that by default GPU offloading is off (i haven't seen one yet), but **reading the docs is probably a better solution than turning this on by default**

**Comment by shibe2** [comment] 2024-06-27 18:49
>None of the work is being done by the gpu, it runs exactly as fast as CPU build and gpu use stays at 0%.

How long is your prompt?

**Comment by differentprogramming** [comment] 2024-06-27 18:53
Another question, isn't 100% gpu usage for a  5 times uplift vs. a 6 core skylake cpu a bit low?
I can't really know because there's no matrix of uplift per common GPUs, different ways of using them (BLAS, CUDA, Vulkan etc.) and different models and format.
While I realize that would be a combinatorial mess, there should be an entry with some example tokens per second for an example model, a few variations on it, and common GPUs.  And some idea whether CUDA is for instance the fastest and how BLAS or rocBLAS or Vulkan compares.

**Comment by differentprogramming** [comment] 2024-06-27 18:54
For instance I have no idea if I would get any uplift from spending a few weeks Hipifying the CUDA build!

**Comment by differentprogramming** [comment] 2024-06-27 18:57
> > None of the work is being done by the gpu, it runs exactly as fast as CPU build and gpu use stays at 0%.
> 
> How long is your prompt?

I wasn't testing with interactive mode, so it was using built in prompts at random.
I notice that changing the length of the result doesn't change the per token speed reported.

**Comment by dspasyuk** [comment] 2024-06-28 02:21
@differentprogramming It is the intended behavior, you can always default to CPU when everything fails. As for the difference between CUDA and cuBLAS, I do not see much difference on GTX1060/P4/A100/A4500 GPUs  ~about 20 tokens per second on GTX1060 using Llama-instruct-Q4 Here is my default setup: https://github.com/dspasyuk/llama.cui

**Comment by differentprogramming** [comment] 2024-06-28 02:35
A 1060 is very different from an MI50. It has no speedup for 16 bit, 8 bit or 4 bit vs 32 bit numbers.  It's so different that it doesn't tell me much.  I noticed when I was playing with Stable Diffusion that those very old gpus were much slower for inference than similarly speced newer ones.

**Comment by differentprogramming** [comment] 2024-06-28 02:39
I deleted a reply because I hadn't noticed that dspasyuk had mentioned lots of gpus other than his 1060.

**Comment by dspasyuk** [comment] 2024-06-28 03:46
@differentprogramming No worries, GTX1060 is about 10 times slower than A4500 (~200 tokens/s) and A100 (PCIE card) is about 180 tokens per/sec using Llama3-instract-q4 and yesterday's version of llama.cpp with llama.cui

**Comment by shibe2** [comment] 2024-06-28 04:22
So I benchmarked prompt processing with -ngl 0 with 3 back-ends: CPU, Vulkan and hipBLAS.

| model                          |       size |     params | backend    | threads |          test |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | ------: | ------------: | ---------------: |
| llama 8B Q6_K                  |   6.14 GiB |     8.03 B | CPU        |       8 |         pp128 |     33.53 ± 0.12 |
| llama 8B Q6_K                  |   6.14 GiB |     8.03 B | CPU        |       8 |         pp256 |     32.75 ± 0.07 |
| llama 8B Q6_K                  |   6.14 GiB |     8.03 B | CPU        |       8 |         pp512 |     31.75 ± 0.02 |
| llama 8B Q6_K                  |   6.14 GiB |     8.03 B | CPU        |       8 |        pp1024 |     31.06 ± 0.01 |
| llama 8B Q6_K                  |   6.14 GiB |     8.03 B | CPU        |       8 |        pp2048 |     29.62 ± 0.00 |

| model                          |       size |     params | backend    | ngl |          test |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ------------: | ---------------: |
| llama 8B Q6_K                  |   6.14 GiB |     8.03 B | Vulkan     |   0 |         pp128 |    113.84 ± 1.78 |
| llama 8B Q6_K                  |   6.14 GiB |     8.03 B | Vulkan     |   0 |         pp256 |    200.53 ± 0.82 |
| llama 8B Q6_K                  |   6.14 GiB |     8.03 B | Vulkan     |   0 |         pp512 |    273.84 ± 0.76 |
| llama 8B Q6_K                  |   6.14 GiB |     8.03 B | Vulkan     |   0 |        pp1024 |    272.64 ± 0.82 |
| llama 8B Q6_K                  |   6.14 GiB |     8.03 B | Vulkan     |   0 |        pp2048 |    270.03 ± 0.55 |

| model                          |       size |     params | backend    | ngl |          test |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ------------: | ---------------: |
| llama 8B Q6_K                  |   6.14 GiB |     8.03 B | CUDA       |   0 |         pp128 |    308.72 ± 0.05 |
| llama 8B Q6_K                  |   6.14 GiB |     8.03 B | CUDA       |   0 |         pp256 |    436.04 ± 0.05 |
| llama 8B Q6_K                  |   6.14 GiB |     8.03 B | CUDA       |   0 |         pp512 |    539.76 ± 0.16 |
| llama 8B Q6_K                  |   6.14 GiB |     8.03 B | CUDA       |   0 |        pp1024 |    527.57 ± 0.29 |
| llama 8B Q6_K                  |   6.14 GiB |     8.03 B | CUDA       |   0 |        pp2048 |    497.41 ± 0.93 |

build: a27aa50a (3258)

The last table says "CUDA", but it actually used AMD GPU, and CUDA was not installed on the test system.

As we can see, GPU offloading provides significant speedup in prompt processing. I use some models with -ngl 0, and there, GPU back-ends provide speedup in real use-cases too.

The title of this issue purports that _all_ work is done on CPU by default, which is not the case in my experience and tests.

What is true is that processing of small prompts and generation does not use GPU with -ngl 0. This is intentional because when model parameters are not stored in VRAM, they need to be repeatedly transferred from system RAM for each token or small batch, which takes time and negates the speedup provided by GPU.

The remaining question is whether ngl should be 0 by default. Ideally, the value for ngl could be selected automatically for best performance. Some work in this direction is done in #6502. Unfortunately, this is difficult to figure out in most cases. For example,  hipBLAS back-end allocates additional VRAM during inference, and it can run out of it even if parameters and initially allocated buffers seem to fit in VRAM. Also, smaller value for ngl was sometimes faster in my tests.

Not having a good solution, here are some options for default ngl value:

- 0 – this is what we have currently. You have to find values that work best on your system for models that you use.
- All layers. We may get get a stream of reports about it crashing when it runs out of VRAM.
- Some value in between – what it should be?

I'm closing this issue, because everything seems to work as expected. If you want to discuss automatic ngl, there is issue #3719 about that.

**Closed by shibe2** 2024-06-28 04:22 UTC
Labels: bug-unconfirmed, medium severity

**Comment by differentprogramming** [comment] 2024-06-28 08:29
@shibe2 is there a simple command line to run the same test on my system?

**Comment by shibe2** [comment] 2024-06-28 09:10
For example:

    llama-bench -m models/llama3-8b-instruct/ggml-model-q8_0.gguf -p 128,256,512,1024,2048 -n 0 -ngl 0

For testing different back-ends I used different builds of llama-bench.

**Comment by differentprogramming** [comment] 2024-06-28 10:07
I hate to keep bothering you, but what does it mean that in llama-cli I get
about 50 t/s but that bench test reports 240?

**Comment by shibe2** [comment] 2024-06-28 10:27
@differentprogramming I benchmarked specifically processing of long prompts. If you don't give it a prompt of the same length as used in the benchmark, you will get different speeds, of course.

**Comment by shibe2** [comment] 2024-07-06 13:02
Larger batches are processed on GPU, I think, 32 tokens and up. Model's parameters involved in each operation are transferred to VRAM, then discarded after the operation is completed.

**Comment by Msyu1020** [comment] 2024-07-06 13:15
> Larger batches are processed on GPU, I think, 32 tokens and up. Model's parameters involved in each operation are transferred to VRAM, then discarded after the operation is completed.

Thanks a lot. Could you point the related code of llama.cpp that determines whether the batch is large enough to be processed on the GPU?

**Comment by shibe2** [comment] 2024-07-06 14:14
I'm not familiar with that code, but I think that this is relevant: https://github.com/ggerganov/llama.cpp/blob/87e25a1d1bd26eb06d1cab9e2ee4e14a7a0be33c/ggml/src/ggml-backend.c#L1172-L1180
Operations in non-offloaded layers are normally performed by CPU back-end. But if `ggml_backend_offload_op` of the other back-end returns true, it will be performed by that back-end instead. GPU back-ends check batch dimension of result tensor against some threshold (32), and then return true for most operations. For example, this is relevant code in Vulkan back-end: https://github.com/ggerganov/llama.cpp/blob/87e25a1d1bd26eb06d1cab9e2ee4e14a7a0be33c/ggml/src/ggml-vulkan.cpp#L6349-L6352

**Comment by Msyu1020** [comment] 2024-07-06 14:24
> I'm not familiar with that code, but I think that this is relevant:
> 
> https://github.com/ggerganov/llama.cpp/blob/87e25a1d1bd26eb06d1cab9e2ee4e14a7a0be33c/ggml/src/ggml-backend.c#L1172-L1180
> 
> 
> Operations in non-offloaded layers are normally performed by CPU back-end. But if `ggml_backend_offload_op` of the other back-end returns true, it will be performed by that back-end instead. GPU back-ends check batch dimension of result tensor against some threshold (32), and then return true for most operations. For example, this is relevant code in Vulkan back-end:
> https://github.com/ggerganov/llama.cpp/blob/87e25a1d1bd26eb06d1cab9e2ee4e14a7a0be33c/ggml/src/ggml-vulkan.cpp#L6349-L6352

This is exactly what I want.  Sincerely thank you

**Comment by shibe2** [comment] 2024-07-06 14:38
@Msyu1020 This is completely off-topic, but it would be nicer if you didn't quote long comments if full.
