### ISSUE TITLE
iOS library is broken because ggml dependency is not pinned 

### ISSUE THREAD

**Issue by azarovalex** [ggerganov/llama.cpp#4867] opened 2024-01-11 02:26 UTC
I was debugging some accidental crashes in SwiftUI sample, dug deeper and understood a couple of things.

### Some background

1. When llama.cpp is built outside of Xcode, e.g. with make, there is no direct dependency on [ggml repo](https://github.com/ggerganov/ggml). ggml sources are just duplicated in this repo, they get out of sync but there are [scripts](https://github.com/ggerganov/ggml/tree/5a3154b59242d17b2225872a2538d341f4f28c54/scripts) used to sync two repos + whisper.cpp, which also use ggml.

2. Xcode build is different (not only the sample, but all external applications that use llama.cpp through SPM). In this case ggml will be fetched from [ggml repo](https://github.com/ggerganov/ggml), ignoring files present in this repo. Additionally, dependency on ggml repo [is not pinned](https://github.com/1-ashraful-islam/llama.cpp/blob/5f12e26899f50f177d2133e52d4b883c1189333f/Package.swift#L17), which technically means that ggml can be resolved to *any* commit.

### Why it's done like this and why it doesn't work

This difference in build logic between Xcode and make was introduced only recently in [this PR](https://github.com/ggerganov/llama.cpp/pull/4691/files). 
I completely see [the reasoning](https://github.com/ggerganov/llama.cpp/pull/4691#issue-2060383529) behind this change, indeed whisper.cpp already has it's own copy of ggml, so we got a conflict of sybmols in the resulting binary if we used both llama.cpp and whisper.cpp in one iOS app.

However the current approach just doesn't work for llama.cpp at all. For example right now latest `master` of llama.cpp (cd108e6) is not compatible with the latest master of `ggml` (c75db1e), it leads to a crash [on this line](https://github.com/ggerganov/llama.cpp/blob/cd108e641dbdedd8c5641c4cec1762f751f38136/ggml.c#L4772).

### Proposed solution

I really don't want to force Grigori to rethink how he structures his projects, in this case a monorepo might solve the problem, but I guess iOS build just has to adapt to the existing structure.
The best solution I see so far:

-  We create a new target in [the SPM manifest](https://github.com/ggerganov/llama.cpp/blob/4aa73e37b01a8bdb36c9ff38e7e1ba20c456afb9/Package.swift#L20C10-L20C10). It will build llama.cpp exactly how `make` does it, using local ggml sources and without dependency on external repo. This new target becomes the recommended way to integrate llama.cpp to any iOS app, because it's guaranteed to always build the same sources as other build systems. (this step is basically a revert of #4691)
- For rare cases when an app already has ggml, like with `whisper.cpp`, we create a second target that uses ggml from the external repo and the developer of the app will be responsible for pinning a compatible version, ensuring two commits of llama and ggml work together. (This target is exactly the target we have right now)
- Finally we add a CI job that builds the sample, so this won't happen again. 😄

I'd love to hear opinions on this possible solution from folks who previously contributed into SPM manifest: @ggerganov @1-ashraful-islam @kchro3 @jhen0409.

**Comment by ggerganov** [comment] 2024-01-11 08:04
Thank you for creating the issue and summarizing the problem - this helps. I think the main trouble came from me overlooking the dependency problem of the Swift package when we merged #4691. Should be possible to resolve by simply pinning to a specific `ggml` commit like we just did in `whisper.cpp`: https://github.com/ggerganov/whisper.cpp/commit/cc7f872131b355529f5ca23c62db4455b366f8a1

However, there is still one issue that would remain - the `ggml.h` header in the `spm-headers` folder. Can we eliminate this and make the `llama.cpp` Swift package simply use the `ggml.h` header from the `ggml` package? Ideally, we should be able to simply remove the `ggml.h` symbolic link from `spm-headers`. Will be testing out this later today - any feedback in the meantime is appreciated.

The 2-target solution is also an option, but not sure if it is better.

Btw, #4822 is likely unrelated to the current build issues.

> However the current approach just doesn't work for llama.cpp at all. For example right now latest master of llama.cpp (https://github.com/ggerganov/llama.cpp/commit/cd108e641dbdedd8c5641c4cec1762f751f38136) is not compatible with the latest master of ggml (c75db1e), it leads to a crash [on this line](https://github.com/ggerganov/llama.cpp/blob/cd108e641dbdedd8c5641c4cec1762f751f38136/ggml.c#L4772).

Can you double-check this? The crash initially was caused by the introduction of the new quantization type which changed the enum value for `GGML_TYPE_I32` in the `ggml.h` header. However, after syncing the 2-bit changes to `ggml` (https://github.com/ggerganov/ggml/commit/8a547fe1025b6968de94f1bf6294928b5dfb6ae5) it should no longer be an issue.

**Comment by ggerganov** [comment] 2024-01-11 15:59
Could you guys review https://github.com/ggerganov/llama.cpp/pull/4878 and let me know if it works for you and if you think this is a good way to proceed with `llama.cpp` Swift package

**Comment by 1-ashraful-islam** [comment] 2024-01-11 19:03
@to3d I made the three pull requests to specifically allow importing both llama.cpp and whisper.cpp in to a single iOS app using SPM. I did not run into the the current issue of needing to pin the ggml dependency at that time.

See:
* https://github.com/ggerganov/ggml/pull/674
* https://github.com/ggerganov/llama.cpp/pull/4691
* https://github.com/ggerganov/whisper.cpp/pull/1701

**Closed** 2024-01-11 19:31 UTC
Labels: bug-unconfirmed

**Comment by ggerganov** [comment] 2024-01-11 19:33
For now I merged the pinned commit version. I just figured we can make the packages track a `release` branch in `ggml` and when we sync the repos, we'll update the release branch and it should be all good.

**Comment by ggerganov** [comment] 2024-01-11 20:01
Both `llama.cpp` and `whisper.cpp` Swift packages now reference the `release` branch of `ggml`. Let me know if you run into any problems

**Comment by ggerganov** [comment] 2024-01-11 20:28
> Pinning to a branch is still not perfect, it's not forcing Xcode to fetch the latest commit each time, some resolved hash is stored in Package.resolved and it can get out of sync with resolved commit of llama.cpp itself.

AFAIK in these cases Xcode -> File -> Packages -> Update to Latest Package Versions should help

**Comment by pgorzelany** [comment] 2024-02-02 21:48
Just run into this issue. I have updated llama.cpp to the latest release version but the ggml dependency was not updated automatically because of `Package.resolved`. Had to read through a couple of threads to find the solution. I deleted the `Package.resolved` file and fetched both dependencies again.
