### ISSUE TITLE
How to use it in Python

### ISSUE THREAD

**Issue by Genolium** [ggerganov/llama.cpp#253] opened 2023-03-18 04:46 UTC
How to use this in my python code?

**Comment by j-f1** [comment] 2023-03-18 04:57
Right now the best option is to call out to it using `subprocess` like any other shell command. Soon (see #77) it will be possible to access it from C++ bindings which someone would have to write to make it importable from Python.

**Comment by j-f1** [comment] 2023-03-18 04:58
Closing as duplicate of https://github.com/ggerganov/llama.cpp/issues/82.

**Closed by j-f1** 2023-03-18 04:58 UTC
