### ISSUE TITLE
Misc. bug: Windows prebuilt binaries not working since b4191

### ISSUE THREAD

**Issue by waltersamson** [ggerganov/llama.cpp#10944] opened 2024-12-22 13:52 UTC
### Name and Version

llama-b4191-bin-win* and onwards

### Operating systems

Windows 10

### Problem description & steps to reproduce

Relevant discussion: https://github.com/ggerganov/llama.cpp/discussions/10926

- Download prebuilt windows binaries since b4191, such as llama-b4191-bin-win-avx2-x64.zip
- Extract and run llama-server.exe or llama-cli.exe

Actual behavior:
No output in terminal, the program just returns.
No error message of any kind, no terminal output, just terminates.

Expected behavior:
It should print out messages such as "build: 4179 (25669aa9) with MSVC 19.29.30157.0 for x64"

### First Bad Commit

First bad build is b4191:
```
├─llama-b3598-bin-win-avx2-x64-GOOD
├─llama-b3982-bin-win-avx2-x64-GOOD
├─llama-b4056-bin-win-avx2-x64-GOOD
├─llama-b4139-bin-win-avx2-x64-GOOD
├─llama-b4171-bin-win-avx2-x64-GOOD
├─llama-b4177-bin-win-avx2-x64-GOOD
├─llama-b4178-bin-win-avx2-x64-GOOD
├─llama-b4179-bin-win-avx2-x64-GOOD
├─llama-b4191-bin-win-avx2-x64-BAD
├─llama-b4200-bin-win-avx2-x64-BAD
├─llama-b4226-bin-win-avx2-x64-BAD
└─llama-b4375-bin-win-avx2-x64-BAD
```

### Relevant log output

No log output available, the program just quits:
```shell
C:\Users\ws\Desktop\test_llamacpp_bin\llama-b4191-bin-win-avx2-x64-BAD>llama-cli.exe

C:\Users\ws\Desktop\test_llamacpp_bin\llama-b4191-bin-win-avx2-x64-BAD>llama-server.exe

C:\Users\ws\Desktop\test_llamacpp_bin\llama-b4191-bin-win-avx2-x64-BAD>
```

**Comment by phil-scott-78** [comment] 2024-12-22 19:28
fwiw, this is what I'm seeing just trying to download it in chrome. wonder if windows defender is blocking the execution

![image](https://github.com/user-attachments/assets/bdad2961-51a1-4342-8654-d286dff5dc7e)

**Comment by slaren** [comment] 2024-12-23 00:12
Duplicate of #10929

**Closed by slaren** 2024-12-23 00:12 UTC
Labels: bug-unconfirmed

**Comment by Martin-HZK** [comment] 2024-12-30 10:30
I resolve the issue by upgrading the MSVC version. I strongly recommend that you upgrade the MSVC version from Microsoft official website. @waltersamson

**Comment by waltersamson** [comment] 2024-12-31 14:46
> I resolve the issue by upgrading the MSVC version. I strongly recommend that you upgrade the MSVC version from Microsoft official website. @waltersamson

Thanks! I updated MS vcredist 2015-2022 to version 14.42.34433.0 and it works now.

**Comment by Martin-HZK** [comment] 2024-12-31 14:56
Great! Glad to hear that!
