### ISSUE TITLE
Llama.cpp GPU Offloading Issue Langchain Wrapper

### ISSUE THREAD

**Issue by MontassarTn** [ggerganov/llama.cpp#6769] opened 2024-04-19 15:50 UTC
Code:
llm = LlamaCpp( model_path=model_path,
n_ctx= 2048, max_tokens=250, verbose=True, n_gpu_layer= -1, n_batch=512, temperature=0.3, top_p=0.95, top_k=40, min_p=0.05,
)
Blas = 1 but 0 offloading on GPU layers then it runs on CPU

**Comment by slaren** [comment] 2024-04-19 17:00
Duplicate of #6742

**Closed by slaren** 2024-04-19 17:00 UTC
Labels: bug-unconfirmed
