### ISSUE TITLE
@ggerganov!!! Why can't llama.cpp be used on the server side to provide one-to-many services?

### ISSUE THREAD

**Issue by jygmysoul** [ggerganov/llama.cpp#8193] opened 2024-06-28 14:52 UTC
### Discussed in https://github.com/ggerganov/llama.cpp/discussions/8191

<div type='discussions-op-text'>

<sup>Originally posted by **jygmysoul** June 28, 2024</sup>
I read the code of server.cpp and parallel.cpp of llama.cpp.
I found that llama.cpp actually shared the same llama_context and llama_batch when dealing with multiple users on the server.
This made me very confused and shocked.

Because in general, the context of llama_context is only 4000. When it is assumed that only 10 users are provided with services, 4000/10=400 means that the context length that each user can use is only 400.
This length cannot even accommodate a complete conversation. This makes AI become like a goldfish with only 10 seconds of memory.

In addition, the content of multiple users must be merged into the same llama_batch for submission. In the case of the same batch, it will happen that the fast user must wait for the slow user!
Not to mention that when the context is insufficient, the old context space needs to be discarded. This discarding needs to be calculated and processed.

Why is llama.cpp designed like this? Can't each user have a separate llama_context and llama_batch?
Isn't the meaning of llama_context to isolate users? What's the meaning of batch submission processing?
Why is it designed like this?

Did I understand it wrong?
Is it because llama.cpp only considers single-user usage scenarios?
Is it because of the limitations of the underlying LLAMA and Transformer?
Is it because of the commercial restrictions of llama.cpp? How to remove it?

My goal is to directly call the llama.cpp library and integrate it directly into our company's server framework, rather than directly using the server.cpp example.
Today I tried to use multi-threading to create multiple llama_contexts to isolate each customer, but failed, and finally crashed in a mem operation inside llama.cpp.
Obviously failed, I guess the underlying architecture is caused by merging and sharing together.

How should I solve this problem? I hope that each customer's llama_context is independently isolated and has its own independent context length.
Finally, please give feedback as soon as possible, thank you for your help.</div>

**Comment by Green-Sky** [comment] 2024-06-28 15:24
duplicate of https://github.com/ggerganov/llama.cpp/discussions/8191 and https://github.com/ggerganov/llama.cpp/issues/8192

@jygmysoul please dont spam and scream, or you will be banned. Also This is not a paid customer support hotline you pay to have available too you.

**Closed by Green-Sky** 2024-06-28 15:24 UTC
