### ISSUE TITLE
Feature Request: llamacppp server - generated syntax code coloring 

### ISSUE THREAD

**Issue by mirek190** [ggerganov/llama.cpp#10800] opened 2024-12-12 13:50 UTC
### Prerequisites

- [X] I am running the latest code. Mention the version if possible as well.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I searched using keywords relevant to my issue to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new and useful enhancement to share.

### Feature Description

Hello

Can you add a generated syntax code coloring?
Currently llamacpp server is awesome but missing coloring code generated ;)   

![Screenshot 2024-12-12 134330](https://github.com/user-attachments/assets/489ff4d4-39a3-4dcf-931f-d2d182b25557)

### Motivation

Colored syntax would be more readable

**Comment by ggerganov** [comment] 2024-12-12 15:58
Duplicate of #10246

**Closed by ggerganov** 2024-12-12 15:58 UTC
Labels: enhancement
